name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Swift 6.0 Toolchain
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "6.0"

    - name: Check Swift Version
      run: swift --version

    - name: Build
      run: swift build

    - name: Run Tests
      run: swift test --enable-code-coverage