name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select swift version
      uses: fwal/setup-swift@v1
      with:
        swift-version: 6.0.0
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
